// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgzxicwidbaqhkmpibey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnenhpY3dpZGJhcWhrbXBpYmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODkzMDAsImV4cCI6MjA2MDA2NTMwMH0.v61AS0RPya8WnIFCLXWRW31-838uyRY-e_zomV536mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);